

var options = {
				   solution: 			[[null,	null,	null,	null,	null,	null,	null,	null,	null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,  null],
		                                [null,	null,	null,	null,	null,	null,	null,	null,	null,   null,   null,   null,   null,   null,   null,   null,   null,   'S',    null,  null],
		                                [null,	null,	null,	null,	null,	null,	null,	null,	null,   null,   null,   null,   null,   null,   null,   null,   null,   'I',    null,  null],
		                                [null,	null,	null,	null,   'S',	'P',	'E',	'E',	'C',	'H',    null,   null,   null,   null,   null,   null,   null,   'L',    null,  null],
		                                [null,	null,	null,	null,	null,	null,	null,	null,	null,   'E',    null,   null,   null,   null,   null,   null,   null,   'E',    null,  null],
		                                [null,	null,	null,	'A',	'G',	'R',	'I',	'C',	'U',    'L',    'T',    'U',    'R',    'E',    null,   null,   null,   'N',    null,  null],
		                                [null,	null,	null,	null,	null,	null,	null,	null,	null,   'E',    null,   null,   null,   null,   null,   null,   null,   'C',    null,  null],
		                                [null,	null,	null,	'P',	null,	null,	null,	null,	null,   'V',    null,   'R',    'E',    'M',    'E',    'D',    'I',    'E',     'S',  null],
		                                [null,	null,	'P',	'R',	'E',	'A',	'M',	'B',	'L',    'E',    null,   null,   null,    null,   null,  null,  null,    null,   null,  null],
		                                [null,	null,	null,	'O',	null,	null,	null,	null,   null,   'N',    null,   null,   'A',    'M',    'B',    'E',     'D',    'K',    'A',   'R'],
		                                [null,	null,	null,	'T',	null,	null,	null,	null,	null,   null,   null,   'H',    null,    null,   null,   null,  null,   null,  null,   null],
		                                [null,	null,	null,	'E',	null,	null,	null,	null,   null,   'P',    'E',    'A',    'C',    'E',    null,   null,   null,   null,  null,   null],
		                                [null,	null,	null,	'C',	null,	null,	null,	null,	null,   null,   'Q',    'R',    null,   'I',    null,   null,   null,   null,  null,   null],
		                                [null,	null,	null,	'T',	null,   null,	null,	null,	null,   null,   'U',    'M',    null,   'G',    null,   null,   null,   null,  null,   null],
		                                [null,	null,	null,	null,	null,	null,	null,	null,	null,   null,   'A',    'O',    null,   'H',    null,   null,   null,   null,  null,   null],
		                                [null,	null,	null,	null,	null,   null,   null,   null,   null,   null,   'L',    'N',    null,   'T',    null,   null,   null,   null,  null,   null],
		                                [null,	null,	null,	null,	null,	null,	null,	null,	null,   null,   'I',    'Y',    null,   'H',    null,   null,   null,   null,  null,   null],
		                                [null,	null,	null,	null,	null,	null,	null,	null,	null,   null,   'T',    null,   null,   null,   null,   null,   null,   null,  null,   null],
		                                [null,	null,	null,	null,	null,	null,	null,	null,	'P',    'A',    'Y',    null,   null,   null,   null,   null,   null,   null,  null,   null],
		                                [null,	null,	null,	null,	null,	null,	null,	null,	null,   null,   null,   null,   null,   null,   null,   null,   null,   null,  null,   null]],


		            index: 				[[null,  null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null],
		                                [null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,     13,   null,   null],
		                                [null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null],
		                                [null,   null,   null,   null,      1,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null],
		                                [null,   null,   null,   null,   null,   null,   null,   null,   null,      2,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null],
		                                [null,   null,   null,      3,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null],
		                                [null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null],
		                                [null,   null,   null,      5,   null,   null,   null,   null,   null,   null,   null,      6,   null,   null,   null,   null,   null,   null,   null,   null],
		                                [null,   null,      8,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null],
		                                [null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,     11,   null,   null,   null,   null,   null,   null,   null],
		                                [null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,      4,   null,   null,   null,   null,   null,   null,   null,   null],
		                                [null,   null,   null,   null,   null,   null,   null,   null,   null,      9,     10,   null,   null,     12,   null,   null,   null,   null,   null,   null],
		                                [null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null],
		                                [null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null],
		                                [null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null],
		                                [null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null],
		                                [null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null],
		                                [null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null],
		                                [null,   null,   null,   null,   null,   null,   null,   null,      7,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null],
		                                [null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null]],

		         questions_across: [	  "1. Which Article guarantees the 'Right to Freedom of Speech and Expression'?",
		                                  "3. Which Directive Principle deals with the 'Organization of Agriculture and Animal husbandry'?",
		                                  "6. Which Fundamental Right is often referred to as the 'Heart and Soul' of the Indian Constitution?",
										  "7. Which Article advocates for 'Equal pay for equal work' for men and women?",
		                                  "8. What term is used for the introduction to the Constitution, which states the objectives of the Constitution?",
		                                  "9. Which Directive Principle encourages the State to promote 'International Peace and Security'?",
										  "11. Who is known as the 'Father of the Indian Constitution'?"],

		         questions_down: [		 "2. How many Fundamental Duties are listed in the Constitution of India?",
		                                 "4. What is the duty to 'Promote Harmony'?",
		                                 "5. What is the duty to 'Safeguard Public Property'?",
		                                 "10. What is the right that ensures 'Eequality of Opportunity' in public employment?",
										 "12. Which Schedule of the Indian Constitution lists the 'Languages recognized by the Constitution'?",
										 "13. Which Fundamental Right ensures protection against 'self-incrimination'?"],

	};


		cwp_nmsp.activateCWP(document.getElementById("myPuzzle"),false,options);